### ISSUE TITLE
[Feature Request] Respect $XDG_CONFIG_HOME path

### ISSUE THREAD

**Issue by amiroslaw** [bergercookie/syncall#58]
From 2.6.0 taskwarrior version it attempts to find config file at '$XDG_CONFIG_HOME/task/taskrc'. Unfortunately taskwarrior-syncall prints error if can't find `.taskrc` in home folder. 
IDK if this issue should be a BUG.

```
Traceback (most recent call last):
  File "/home/miro/.local/bin/tw_gcal_sync", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/miro/.local/lib/python3.10/site-packages/taskwarrior_syncall/scripts/tw_gcal_sync.py", line 142, in main
    tw_side = TaskWarriorSide(tags=tw_tags, project=tw_project)
  File "/home/miro/.local/lib/python3.10/site-packages/taskwarrior_syncall/taskwarrior_side.py", line 53, in __init__
    self._tw = TaskWarrior(marshal=True, config_filename=config_file)
  File "/home/miro/.local/lib/python3.10/site-packages/taskw/warrior.py", line 438, in __init__
    super(TaskWarriorShellout, self).__init__(config_filename)
  File "/home/miro/.local/lib/python3.10/site-packages/taskw/warrior.py", line 62, in __init__
    self.config = TaskWarriorBase.load_config(config_filename)
  File "/home/miro/.local/lib/python3.10/site-packages/taskw/warrior.py", line 180, in load_config
    return TaskRc(config_filename, overrides=overrides)
  File "/home/miro/.local/lib/python3.10/site-packages/taskw/taskrc.py", line 58, in __init__
    config = self._read(self.path)
  File "/home/miro/.local/lib/python3.10/site-packages/taskw/taskrc.py", line 96, in _read
    with codecs.open(path, 'r', 'utf8') as config_file:
  File "/usr/lib/python3.10/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/home/miro/.taskrc'
``` 

#### versions
tw_gcal_sync, version 1.2.1
taskwarrior 2.6.2

**Comment by bergercookie** [comment]
If the `taskrc` file is not under `~/.taskrc` then you should be specifying it via the TASKRC environment variable.

```
TASKRC = os.getenv("TASKRC", "~/.taskrc")
```

This should work AFAICT. If it doesn't please reproduce with latest version and we can re-open.

**Comment by cenktaskin** [comment]
As far as I can try, syncall works with the env variable as you mentioned but the taskwarrior doesn't require this environment variable and check $XDG_CONFIG_HOME/task/taskrc by default. 

Changing this behaviour can remove the repeated 
```sh
TASKRC override: /home/user/.config/task/taskrc
```
prompts while using taskwarrior.

**Comment by bergercookie** [comment]
Hi @cenktaskin , 

> From 2.6.0 taskwarrior version it attempts to find config file at '$XDG_CONFIG_HOME/task/taskrc'

Yeah, I re-read @amiroslaw 's original description and since this is the behavior with newer taskwarrior versions, it should also be supported by `syncall`.

I'll re-open this ticket.

Happy to accept PRs for this :)
