### ISSUE TITLE
[BUG] traceback with latest (ImportError: cannot import name 'TaskWarriorSide' from 'syncall)

### ISSUE THREAD

**Issue by bcohen44** [bergercookie/syncall#66]
I have python 3.10, and install the latest syncall from pip3.

```
w_gcal_sync --help
Traceback (most recent call last):
  File "/home/BOSDYN/bcohen/.local/bin/tw_gcal_sync", line 5, in <module>
    from syncall.scripts.tw_gcal_sync import main
  File "/home/BOSDYN/bcohen/.local/lib/python3.10/site-packages/syncall/scripts/tw_gcal_sync.py", line 21, in <module>
    from syncall import (
ImportError: cannot import name 'TaskWarriorSide' from 'syncall' (/home/BOSDYN/bcohen/.local/lib/python3.10/site-packages/syncall/__init__.py)
```

**Comment by bergercookie** [comment]
Hi there,

What do the following commands say?

```
pip3 show syncall
pip3 show taskwarrior-syncall
```

**Comment by bergercookie** [comment]
`taskw` is now an extra.
Could you try installing that first?

```
pip3 install syncall[tw,google]
```
